### ISSUE TITLE
encoder.tflite的模型输入问题

### ISSUE THREAD

**Issue by zjzhengyin** [litun5315/SS-watermark#1]

**Comment by zjzhengyin** [comment]
不用了哈，我已经解决

**Comment by l1teng** [comment]
Our android implementation of StegaStamp is based on online operation, therefore sorry for can not
provide helpful advice for you with the issue that you meet when processing android-integrated Stegastamp model. 
Moreover, please use English to put forward issues, so that others can understand your issues and may give some instructive advice.
